from __future__ import annotations

import argparse, hashlib, json, subprocess
from datetime import UTC, datetime
from pathlib import Path

from shiproom.console import write_submission

def main() -> int:
    parser=argparse.ArgumentParser(); parser.add_argument("--release", default="release-state/release.json"); parser.add_argument("--receipt", default="hermes-receipts/receipt.json"); parser.add_argument("--verified", default="submission/verified.json"); parser.add_argument("--runtime", default="runtime-provenance/controlled.json"); parser.add_argument("--output", default="dist"); args=parser.parse_args()
    release=json.loads(Path(args.release).read_text(encoding="utf-8")); receipt=json.loads(Path(args.receipt).read_text(encoding="utf-8")); verified=json.loads(Path(args.verified).read_text(encoding="utf-8")); output=Path(args.output)
    verified["deployed_commit"]=subprocess.check_output(["git","rev-parse","HEAD"],text=True).strip(); verified["generated_at"]=datetime.now(UTC).isoformat()
    runtime=json.loads(Path(args.runtime).read_text(encoding="utf-8")) if Path(args.runtime).exists() else None
    run=write_submission(release,receipt,verified,output,runtime=runtime)
    index=(output/"index.html").read_text(encoding="utf-8"); report=(output/"release-report.html").read_text(encoding="utf-8")
    etag=lambda value: f'"sha256-{hashlib.sha256(value.encode()).hexdigest()}"'
    generated="// Generated by scripts/build_submission.py from disclosure-audited public assets.\n"+f"export const INDEX_HTML={json.dumps(index,ensure_ascii=False)};\nexport const REPORT_HTML={json.dumps(report,ensure_ascii=False)};\nexport const INDEX_ETAG={json.dumps(etag(index))};\nexport const REPORT_ETAG={json.dumps(etag(report))};\n"
    Path("cloudflare/generated_public.js").write_text(generated,encoding="utf-8")
    print(json.dumps({"output":str(output),"release_id":run["release_id"],"assets":sorted(p.name for p in output.iterdir())},indent=2)); return 0
if __name__ == "__main__": raise SystemExit(main())
