"""Frozen, concrete Sessions 6--8 requirement semantics.

Unlike the retired name-to-sentence generator, every entry below states the
observable product invariant.  The catalogue is input to the inventory build;
it is never treated as evidence that the invariant holds.
"""
from __future__ import annotations


BEHAVIORS = {
    # Session 6 -- remediation and closure.
    "S6_ISSUE_AUTHORITY_POLICY": "Every remediation issue classification, actionability decision, automation class, and permitted closure-evidence class is produced by the packaged remediation authority policy from the validated canonical issue inputs.",
    "S6_MODEL_REVIEW_NOT_BLOCKER": "A model-reviewed or candidate concern remains non-blocking and cannot be classified as a verified blocker or receive blocker-grade closure authority.",
    "S6_PLANNER_COMPILER_AUTHORITY": "Planner output may populate only the closed semantic planning fields; compiler-owned issue identity, authority, scope, actionability, automation eligibility, and closure requirements remain unchanged.",
    "S6_HUMAN_OWNER_SEPARATION": "An ordinary human planner result is human_reviewed; owner_declared requires a validated release-bound owner-authority reference and cannot be inferred from transport or actor labels.",
    "S6_OPTIONAL_PLANNER_LIFECYCLE": "Compilation succeeds with zero or one bound planner result, and a missing result yields one minimal packet per actionable issue with every planner-authored field explicitly not_inspected.",
    "S6_AUTOMATION_ELIGIBILITY": "Automation eligibility is derived only from the packaged issue-authority policy and its closed bounded-fix classes, never from filenames, keywords, or reviewer prose.",
    "S6_BOUNDED_FIX_METADATA_ONLY": "bounded_fix_available is metadata in private alpha and exposes no reachable write, fixer, publish, merge, or deployment operation.",
    "S6_REMEDIATION_CARDINALITY": "For three actionable canonical issues, compilation persists exactly three remediation records, three packets, three closure contracts, and three scoped overlay projections without truncation, duplication, or orphans.",
    "S6_PACKET_CONTRACT_LINKS": "Every packet and closure contract reference each other and the same source issue, requirement, criterion, journey, release, and generation through exact stable identifiers.",
    "S6_PACKET_FILE_INTEGRITY": "Every packet and closure-contract file is hash-bound by the generation manifest, belongs to the exact generation file set, and reloads to the same semantic record.",
    "S6_CLOSURE_CONTRACT_COMPLETENESS": "Every actionable issue receives one closed closure contract containing the exact rerun identity, allowed evidence classes, required regression/test/instrumentation outcomes, protected invariants, freshness bindings, and owner requirements.",
    "S6_CLOSURE_EXACT_RERUN": "Closure verification evaluates the exact check or criterion named by the closure contract; an unrelated passing rerun cannot satisfy it.",
    "S6_CLOSURE_PASS_REQUIRED": "A required rerun with a failed result produces unsatisfied and cannot produce satisfied_candidate.",
    "S6_CLOSURE_VERIFIER_INDEPENDENCE": "The verifier identity must be distinct from the fixer identity; a fixer or its receipt cannot verify its own remediation.",
    "S6_CLOSURE_COMMIT_BRANCH_FRESHNESS": "Closure evidence must match the closure contract release, commit, and branch; stale or mismatched evidence produces stale without mutating canonical findings.",
    "S6_CLOSURE_EVIDENCE_CLASS": "Only the closure contract's allowed deterministic evidence classes may support satisfied_candidate; model-reviewed, candidate, or uninspected evidence cannot.",
    "S6_CLOSURE_REGRESSION_REQUIREMENTS": "Every required regression outcome is present, bound to the closure contract, and passing before satisfied_candidate is possible.",
    "S6_CLOSURE_TEST_REQUIREMENTS": "Every required test outcome is present, bound to the closure contract, and passing before satisfied_candidate is possible.",
    "S6_CLOSURE_INSTRUMENTATION_REQUIREMENTS": "Every required instrumentation outcome is present, bound to the closure contract, and passing before satisfied_candidate is possible.",
    "S6_CLOSURE_PROTECTED_INVARIANTS": "Every protected invariant is reported and passing; a missing or failed protected invariant prevents satisfied_candidate.",
    "S6_CLOSURE_OWNER_DECISION": "A closure contract requiring owner action cannot produce satisfied_candidate without the exact validated release-bound owner decision required by that contract.",
    "S6_PRIVATE_ALPHA_NON_MUTATION": "Private-alpha roadmap preparation, compilation, loading, and closure verification never close or rewrite canonical findings, verdicts, Product Intent, graph evidence, or release state.",

    # Session 7 -- review planning and harnesses.
    "S7_SPECIALIST_CATALOGUE": "The review plan uses only the fixed specialist catalogue and exact specialist-to-native-result mapping; no generic or cross-specialist result is accepted.",
    "S7_NATIVE_BOUNDARY_REUSE": "Every selected specialist binds its registered native prepare, work-order, context, result validator, and completion-receipt boundary rather than a weaker planner-owned approximation.",
    "S7_TYPED_SURFACE_POLICY": "Every specialist selection and adaptation is derived through the packaged typed surface policy with explicit source domain, authority, surface, and maximum effect.",
    "S7_SELECTION_EVIDENCE_LINKS": "Every selected, skipped, or unavailable specialist records the exact typed evidence references and applicability authority that caused that state.",
    "S7_PYTHON_SELECTION": "A deterministic Python-project fixture selects python_engineering with Python-scoped native preparation and does not substitute the TypeScript specialist.",
    "S7_TYPESCRIPT_SELECTION": "A deterministic TypeScript-project fixture selects typescript_engineering with TypeScript-scoped native preparation and produces a substantively different plan from the Python fixture.",
    "S7_AI_SELECTION": "A confirmed or candidate typed AI surface selects ai_evaluation with the corresponding bounded authority; not_inspected or filename-only evidence cannot establish confirmed applicability.",
    "S7_BROWSER_EXPLICIT_SKIP": "browser_journey is skipped only when explicit canonical or deterministic evidence establishes explicitly_not_applicable.",
    "S7_BROWSER_ABSENCE_NOT_INSPECTED": "Absence of browser evidence remains not_inspected and never becomes explicitly_not_applicable or a silent skip.",
    "S7_TEST_ADEQUACY_APPLICABILITY": "A typed test-requirement signal selects test_adequacy within the exact linked criterion scope and preserves weaker candidate authority when applicable.",
    "S7_INSTRUMENTATION_APPLICABILITY": "Instrumentation is selected only when a compatible native Measurement preparation and context can be issued for the exact linked scope.",
    "S7_PRODUCT_INTENT_WRAPPER": "The Product Intent wrapper transports an active native packet to intent-proposal.v1, validates it through the existing native validator, and persists only an accepted proposal reference without compiling or strengthening canonical intent.",
    "S7_NATIVE_WORK_ORDER_INTEGRITY": "Every work order binds the exact native preparation, native context, result schema, receipt schema, criteria, evidence, permissions, and immutable semantic hashes.",
    "S7_CODEX_PACKAGE_COMPLETENESS": "A Codex execution package contains every closed package field, derives allowed files from the native preparation, records an explicit native-empty reason when needed, and invokes no harness.",
    "S7_HARNESS_DECLARATION_HONESTY": "Declared capability, granted permission, observed execution, execution receipt, and independence limitation remain separate; a manifest is never represented as proof of isolation.",
    "S7_MANUAL_CODEX_PARITY": "Manual and rendered Codex routes submit the same native result through the same validator and yield identical accepted semantics while preserving distinct transport provenance.",
    "S7_TRUSTED_SUBMISSION_PATHS": "Results and receipts are accepted only from the bound trusted preparation or package inbox; escaped, linked, special, arbitrary, or unexpected files reject.",
    "S7_SUBMISSION_BYTE_PERSISTENCE": "Every submission attempt persists exact result and receipt bytes, snapshot hashes, validation record, attempt number, and work-order binding before any successor plan is published.",
    "S7_REVISION_REQUEST": "The first invalid submission produces exactly one immutable revision request using only the closed compiler reason codes and exact JSON pointers.",
    "S7_CORRECTED_RESULT_ACCEPTANCE": "A second submission is accepted only when it retains the original work-order binding, resolves every requested JSON pointer, passes the native validator, and is persisted in accepted-results.",
    "S7_SECOND_INVALID_FAILURE": "A second invalid submission transitions that specialist to specialist_failed_closed, preserves the rest of the plan, and rejects any third attempt.",
    "S7_FAILED_RESULT_NO_ADAPTATION": "Rejected, revision-required, failed-closed, stale, or superseded results cannot provide active adaptation authority.",
    "S7_TRIGGER_SPECIFIC_EVIDENCE": "Adaptation accepts only the three registered triggers with one exact accepted result and linked typed evidence reference for the same criterion.",
    "S7_MIGRATION_ADAPTATION": "Migration discovery changes the successor plan by selecting migration_and_rollback or recording precise native unavailability and issues a newly bound work order when available.",
    "S7_AI_ADAPTATION": "AI discovery changes the successor plan through the real native Measurement/AI preparation, adding only candidate-scoped work for candidate evidence.",
    "S7_BROWSER_DISPROVEN_ADAPTATION": "Deterministic browser-disproven evidence changes browser work to skipped with explicitly_not_applicable while retaining and superseding the prior work order.",
    "S7_SUPERSEDED_WORK_ORDER_PRESERVATION": "Every adaptation preserves prior work orders immutably and records exact supersession links to any replacement work order.",
    "S7_ADAPTATION_IDEMPOTENCY": "The same trigger, source result, evidence reference, and criterion cannot be applied more than once or re-add equivalent work.",
    "S7_ADAPTATION_CYCLE_DEPTH": "Adaptation remains acyclic and cannot exceed the configured depth of three successor generations.",
    "S7_POINTER_LAST_PUBLICATION": "A successor pointer is replaced only after the new generation is fully written, loaded, and semantically revalidated; late failure preserves the previous pointer.",

    # Session 8 -- contestability.
    "S8_CONTEST_TARGET_REGISTRY": "Every contestation action uses a registered target type and its exact production loader, permitted actions, relevance rule, materiality rule, and owner-decision eligibility.",
    "S8_CONTEST_SOURCE_GENERATION": "The action binds the exact current source generation and release; stale, cross-release, or mixed-generation targets reject.",
    "S8_CONTEST_TARGET_EXISTENCE": "The registry-selected production loader must resolve the exact target record before an action is appended.",
    "S8_CONTEST_EVIDENCE_EXISTENCE": "Actions requiring evidence reference evidence already accepted by an existing compiler; arbitrary or missing payloads reject.",
    "S8_CONTEST_EVIDENCE_RELEVANCE": "Referenced evidence must satisfy the registered target-specific relevance rule rather than merely existing elsewhere in the release.",
    "S8_CONTEST_AUTHORITY_PRESERVATION": "Contestation actions never rewrite finding authority, evidence, Product Intent, graph state, release verdict, or canonical source records.",
    "S8_CONTEST_APPEND_SEQUENCE": "Accepted actions receive a contiguous deterministic sequence in an append-only ledger.",
    "S8_CONTEST_PREVIOUS_HASH": "Every action after the first binds the exact semantic hash of the preceding accepted action.",
    "S8_CONTEST_IDEMPOTENT_REPLAY": "An identical action replay is idempotent and does not append a duplicate ledger record.",
    "S8_CONTEST_CONFLICTING_DUPLICATE": "Reusing an action ID with different semantic content rejects and leaves the ledger unchanged.",
    "S8_CONTEST_OWNER_AUTHORITY": "Owner-only actions require an existing validated release-bound owner-authority object and exact snapshot hash; actor labels, names, emails, prose, or receipts are insufficient.",
    "S8_NAMED_RISK_FACT_NON_MUTATION": "Accepting a named risk changes only the derived owner-decision effect and leaves the target fact, evidence, blocker flag, state, and authority byte-identical.",
    "S8_NAMED_RISK_DECISION_EFFECT": "A valid owner-authorized accept_named_risk action creates the registered accepted-risk decision effect without closing or disproving the target.",
    "S8_OWNER_DECISION_BUDGET": "From at least four eligible decisions, contestability emits exactly two immediate owner decisions and places every remaining decision in overflow.",
    "S8_OWNER_DECISION_PRIORITY": "Owner decisions are ordered by verified blocker requiring owner action, canonical material condition, high-risk unresolved decision, then stable semantic ID.",
    "S8_OWNER_DECISION_OVERFLOW": "Immediate and overflow batches form a complete, unique partition of eligible decisions with exact source links and priority reason codes.",
    "S8_FUTURE_REMEDIATION_NO_CYCLE": "request_remediation records a request consumable only by a future remediation generation and never mutates the current remediation generation or creates a same-generation cycle.",

    # Session 8 -- management artifacts.
    "S8_MANAGEMENT_DEPENDENCY_DISCOVERY": "Management compilation resolves the exact release-bound Product Intent, graph, assessment, Measurement/AI, remediation, review-plan, and contestability dependencies required by the section registry.",
    "S8_MANAGEMENT_DEPENDENCY_STATES": "Every dependency uses exactly required_present, not_applicable, not_used, or unavailable; only required_present carries non-null generation and semantic hash.",
    "S8_MANAGEMENT_DEPENDENCY_FRESHNESS": "Changing any consumed dependency makes the management generation stale, while a later unconsumed optional dependency does not.",
    "S8_MANAGEMENT_MIXED_VECTOR_REJECTION": "Every JSON artifact, HTML metadata block, and GitHub payload contains the same byte-identical dependency vector; mixed vectors reject.",
    "S8_EXECUTIVE_SECTION_COMPLETENESS": "Every required Executive Release Brief section contains the registered substantive records or the exact permitted typed empty state.",
    "S8_PRODUCT_MATRIX_COMPLETENESS": "The Product matrix contains every active criterion exactly once with its exact requirement, journey, evidence, and authority references.",
    "S8_ENGINEERING_SECTION_COMPLETENESS": "Engineering matrices retain exact criterion, test, source, runtime, limitation, and authority references required by their registered selectors.",
    "S8_MEASUREMENT_AI_PASSTHROUGH": "Consumed Measurement/AI records are projected with identical record IDs, substantive values, readiness scopes, and factual and reviewer authorities; management never recomputes them.",
    "S8_REMEDIATION_OVERVIEW_COMPLETENESS": "Remediation overview counts and records exactly match the consumed remediation generation's issues, packets, and closure contracts.",
    "S8_CLOSURE_CONTRACT_INDEXING": "Every closure contract in the consumed remediation generation appears exactly once in the management packet index with its source issue and packet links.",
    "S8_CONTESTABILITY_INCLUSION": "Management artifacts include every consumed contestation action, effect, immediate owner decision, and overflow decision exactly once.",
    "S8_RECOMMENDATION_POLICY": "The private-alpha recommendation is derived only by the packaged recommendation policy from canonical facts and owner-decision effects.",
    "S8_ACCEPTED_CONDITION_EFFECT": "An accepted condition affects only the derived recommendation according to policy and does not rewrite canonical conditions or findings.",
    "S8_NAMED_RISK_RECOMMENDATION_EFFECT": "A valid named-risk decision affects only the derived recommendation according to policy and preserves underlying facts.",
    "S8_INSUFFICIENT_EVIDENCE_STATE": "Missing or unavailable required evidence produces the registered insufficient-evidence recommendation state without fabricated content.",
    "S8_DETERMINISTIC_JSON": "Canonical management JSON is byte-deterministic for the same dependency vector and canonical inputs.",
    "S8_SAFE_HTML": "HTML is a deterministic escaped rendering of canonical JSON with compiler-owned inline CSS only and no scripts, active content, external resources, secrets, or unescaped user HTML.",
    "S8_SAFE_MARKDOWN": "Markdown is a deterministic escaped projection of canonical JSON and cannot introduce executable user-supplied HTML or network publication.",
    "S8_ARTIFACT_HASH_INTEGRITY": "The generation manifest binds every canonical and rendered artifact to its exact byte hash and load rejects any changed artifact.",
    "S8_ARTIFACT_FILE_SET": "A management generation contains exactly the registered JSON, HTML, GitHub JSON, GitHub Markdown, receipt, and manifest files with no unexpected entries.",
    "S8_DETERMINISTIC_RERENDER": "Reloading and rerendering the same canonical generation reproduces byte-identical JSON, HTML, and Markdown outputs.",
    "S8_UPSTREAM_STALENESS": "Loading rederives the dependency vector from current upstream authority and rejects a generation whose consumed dependency changed without rewriting its pointer.",

    # Shared integrity.
    "SHARED_TRUSTED_READS": "Every persisted Sessions 6--8 read uses the trusted-storage boundary and rejects unsafe ancestry, links, special files, traversal, collisions, and unexpected entries.",
    "SHARED_TRUSTED_WRITES": "Every persisted Sessions 6--8 write and atomic replacement validates trusted ancestry and temporary paths before mutation.",
    "SHARED_LINK_REPARSE_SPECIAL_REJECTION": "Real domain-facing preparation, inbox, generation, and pointer operations reject symlinks, reparse points, and special files without side effects.",
    "SHARED_CAPACITY_LIMITS": "Real domain boundaries enforce 256 files, 1 MiB JSON inputs, 2 MiB rendered artifacts, depth eight, and 2,048 canonical records with typed bounded-capacity evidence and no truncation.",
    "SHARED_POINTER_LATE_FAILURE": "Any validation, rendering, or persistence failure before publication leaves the previously valid pointer and generation unchanged.",
    "SHARED_ZERO_PROHIBITED_OPERATIONS": "All 44 frozen security surfaces are independently validated through a real guard or closed-contract unreachability proof with untouched adapters and unchanged state.",
    "SHARED_CONTRACT_INVENTORY": "Multi-source discovery accounts for every packaged, code-defined, and golden-produced Sessions 6–8 contract, with every parity-required contract registered and every exclusion justified.",
    "SHARED_EXECUTED_CONTRACT_PARITY": "Every parity-required contract first passes its Schema and real Python baseline, then rejects distinct structural and semantic mutations while preserving persisted state.",
    "SHARED_BEHAVIORAL_EVAL_INTEGRITY": "The actual behavioral eval runner emits a receipt containing exactly the unchanged 35 case names and all cases pass at the final evidence commit.",
    "SHARED_WORKFLOW_EVAL_INTEGRITY": "The actual workflow runner emits exactly the frozen 18 cases, observed production invocations, independently recomputable assertions, and required canonical artifacts.",
    "SHARED_INSTALLED_WHEEL_LIFECYCLE": "A non-editable wheel installed outside the checkout executes every required connected lifecycle command, preserves raw logs and artifacts, and proves the imported module resides under external site-packages.",
    "SHARED_SKILL_PILOT_CONSISTENCY": "Shiproom skill and pilot materials match the final CLI and closed contracts, retain private-alpha read-only and deferred scope, and contain no publish, merge, deploy, or pilot-execution claim.",
    "SHARED_PROOF_EXECUTION": "Exactly 318 authoritative proofs execute, bind one requirement and fixture class each, measure canonical artifacts, and contain no synthetic observation or unjustified semantic duplicate.",
    "SHARED_CLOSEOUT_GENERATION": "The closeout report and detached receipt are generated only from final-commit JUnit, evals, workflows, proofs, claims, parity, security, wheel, and canonical artifacts with exhaustive requirement equality.",
    "SHARED_INDEPENDENT_VALIDATION": "A separately implemented validator reconstructs every requirement and claim from a self-contained copied bundle and rejects every registered tamper without importing generator or proof decision logic.",
}


if len(BEHAVIORS) != 106:  # pragma: no cover - import-time contract.
    raise RuntimeError("session6_8_requirement_catalogue_count_invalid")
